// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project4

//#include "ui.h"
//
//void button_on(lv_event_t * e)
//{
//	// Your code here
//}
//
//void button_off(lv_event_t * e)
//{
//	// Your code here
//}
