// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: HMI Project1

#ifndef _HMI_PROJECT1_UI_H
#define _HMI_PROJECT1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_onbutton(lv_event_t * e);
extern lv_obj_t * ui_onbutton;
extern lv_obj_t * ui_LabelON;
void ui_event_offbutton(lv_event_t * e);
extern lv_obj_t * ui_offbutton;
extern lv_obj_t * ui_LabelOFF;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_Times40);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
