// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: HMI Project1
//
//#include "ui.h"
//
//void BUTTON_ON(lv_event_t * e)
//{
//	// Your code here
//}
//
//void BUTTON_OFF(lv_event_t * e)
//{
//	// Your code here
//}
