// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: HMI Project1

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_onbutton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_onbutton, 200);
    lv_obj_set_height(ui_onbutton, 200);
    lv_obj_set_x(ui_onbutton, -139);
    lv_obj_set_y(ui_onbutton, 1);
    lv_obj_set_align(ui_onbutton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_onbutton, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_onbutton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_onbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelON = lv_label_create(ui_onbutton);
    lv_obj_set_width(ui_LabelON, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelON, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelON, -2);
    lv_obj_set_y(ui_LabelON, 2);
    lv_obj_set_align(ui_LabelON, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelON, "ON");
    lv_obj_set_style_text_color(ui_LabelON, lv_color_hex(0xF9F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelON, &ui_font_Times40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_offbutton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_offbutton, 200);
    lv_obj_set_height(ui_offbutton, 200);
    lv_obj_set_x(ui_offbutton, 165);
    lv_obj_set_y(ui_offbutton, 5);
    lv_obj_set_align(ui_offbutton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_offbutton, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_offbutton, lv_color_hex(0x1100ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_offbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOFF = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelOFF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOFF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOFF, 167);
    lv_obj_set_y(ui_LabelOFF, 5);
    lv_obj_set_align(ui_LabelOFF, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOFF, "OFF");
    lv_obj_set_style_text_color(ui_LabelOFF, lv_color_hex(0xF6F3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOFF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOFF, &ui_font_Times40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_onbutton, ui_event_onbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_offbutton, ui_event_offbutton, LV_EVENT_ALL, NULL);

}
